[package]
name = "markdown-that"
version = "0.7.0"
authors = [
    "Christopher König <me@kurabloodlust.eu>",
    "Alex Kocharin <alex@kocharin.ru>"
]
description = "Rust port of popular markdown-it.js library."
documentation = "https://docs.rs/markdown-that"
homepage = "https://github.com/z0ne-dev/markdown-that"
repository = "https://github.com/z0ne-dev/markdown-that"
readme = "README.md"
keywords = ["markdown", "commonmark"]
license = "MIT"
categories = ["text-processing", "parsing"]
edition = "2024"

[lib]
name = "markdown_that"
path = "src/lib.rs"

[[bin]]
name = "markdown-that"
path = "src/bin.rs"
doc = false

[features]
default = ["linkify", "syntect"]

[dependencies]
# Lower range limit of these dependencies was manually checked to work with
# minimal versions possible, higher range limit is best guess based on semver.
# So older versions will not work, but newer versions might.
argparse     = ">= 0.2.1, < 0.3"
const_format = ">= 0.1.0, < 0.3"
derivative   = ">= 1.0.2, < 3"
derive_more  = ">= 0.99.0, < 1"
downcast-rs  = ">= 1.0.2, < 2"
entities     = ">= 0.1.0, < 2"
html-escape  = ">= 0.1.0, < 0.3"
linkify      = { version = ">= 0.5.0, < 0.11", optional = true }
mdurl        = ">= 0.3.1, < 0.4"
once_cell    = ">= 1.0.1, < 2"
readonly     = ">= 0.2.0, < 0.3"
regex        = ">= 1.0.0, < 2"
stacker      = ">= 0.1.2, < 0.2"
syntect      = { version = ">= 5.0.0, < 6", optional = true, default-features = false, features = ["default-fancy"] }
unicode-general-category = ">= 0.1.0, < 0.7"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
