[package]
name = "markdown-that"
version = "0.7.0"
authors = [
    "Christopher König <me@kurabloodlust.eu>",
    "Alex Kocharin <alex@kocharin.ru>"
]
description = "Rust port of popular markdown-it.js library."
documentation = "https://docs.rs/markdown-that"
homepage = "https://github.com/z0ne-dev/markdown-that"
repository = "https://github.com/z0ne-dev/markdown-that"
readme = "README.md"
keywords = ["markdown", "commonmark"]
license = "MIT"
categories = ["text-processing", "parsing"]
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
const_format = "0.2.34"
downcast-rs  = ">= 1.0.2, < 2"
educe = "0.6.0"
entities = "1.0.1"
html-escape = "0.2.13"
linkify = { version = "0.10.0", optional = true }
mdurl = "0.3.1"
once_cell    = ">= 1.0.1, < 2"
readonly     = ">= 0.2.0, < 0.3"
regex = "1.11.1"
stacker      = ">= 0.1.2, < 0.2"
syntect      = { version = ">= 5.0.0, < 6", optional = true, default-features = false, features = ["default-fancy"] }
unicode-general-category = ">= 0.1.0, < 0.7"

[features]
default = ["linkify", "syntect"]
